<?php declare(strict_types=1);	
    
    namespace App\Models;
    use App\Models\Batch;

    class Consignment
    {
        private $batch;
        private $db;

        function __construct(Batch $batch, DB $db)
        {
            $this->batch = $batch;
            $this->db = $db;
        }

         /*
        |--------------------------------------------------------------------------
        | Create a new consignment using the id of the current batch, the id of the Courier,
        | and the unique number generated by the algorithm related to the Courier
        |--------------------------------------------------------------------------
        */
        public function createConsignment(string $uniqueNumber, int $courierId)
        {
            $values = [
                'batch_id' => $this->getCurrentBatch(),
                'courier_id' => $courierId,
                'unique_number' => $uniqueNumber,

            ];
            $consignment = $this->db
        				->table('consignments')
						->create($values);
        }
        public function getCurrentConsignments():array
        {
            $consignments = $this->db
                        ->table('consignments')
                        ->select(['unique_number', 'courier_id'])
                        ->where('batch_id','=', $this->getCurrentBatch())
                        ->get();
            return $consignments;
        }

         /*
        |--------------------------------------------------------------------------
        | Get the id of the current Batch from Batch Model
        |--------------------------------------------------------------------------
        */
        private function getCurrentBatch():int
        {
            return $this->batch->getCurrentBatch();
        }


    }